# the BioSample accession
biosample_accession: SAMN26315988

# name of CSV file listing barcode runs to uploade
barcode_runs: barcode_runs.csv

#
sample_name: Bjorkman_Beta_MAP_barcodes

# the following come from the SRA FTP upload instructions
ftp_username: subftp
ftp_account_folder: uploads/agreaney_uw.edu_hNzBp9b0

# Meaningful name for this sample's FTP folder:
ftp_subfolder: Bjorkman_MAP_barcodes
